- name: LINE
  url: https://line.me/ti/p/~kuboon
- name: X-twitter
  url: https://twitter.com/kuboon
- name: Facebook
  url: https://facebook.com/ohkubo.kohei
- name: bsky
  url: https://bsky.app/profile/kbn.one
- name: FB messenger
  url: https://m.me/ohkubo.kohei
- name: Quora
  url: https://jp.quora.com/profile/Ohkubo-Kohei
- name: Threads
  url: https://www.threads.net/@kuboon
- name: Github
  url: https://github.com/kuboon
- name: Zenn
  url: https://zenn.dev/kuboon
- name: Stackoverflow
  url: https://stackoverflow.com/users/683157/kuboon
